/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/battle`; params?: Router.UnknownInputParams; } | { pathname: `/digcrate`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/market`; params?: Router.UnknownInputParams; } | { pathname: `/missions`; params?: Router.UnknownInputParams; } | { pathname: `/pack`; params?: Router.UnknownInputParams; } | { pathname: `/tracklist`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/collection`; params?: Router.UnknownInputParams; } | { pathname: `/collection/[genre]`, params: Router.UnknownInputParams & { genre: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/battle`; params?: Router.UnknownOutputParams; } | { pathname: `/digcrate`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/market`; params?: Router.UnknownOutputParams; } | { pathname: `/missions`; params?: Router.UnknownOutputParams; } | { pathname: `/pack`; params?: Router.UnknownOutputParams; } | { pathname: `/tracklist`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/collection`; params?: Router.UnknownOutputParams; } | { pathname: `/collection/[genre]`, params: Router.UnknownOutputParams & { genre: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/battle${`?${string}` | `#${string}` | ''}` | `/digcrate${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/market${`?${string}` | `#${string}` | ''}` | `/missions${`?${string}` | `#${string}` | ''}` | `/pack${`?${string}` | `#${string}` | ''}` | `/tracklist${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/collection${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/battle`; params?: Router.UnknownInputParams; } | { pathname: `/digcrate`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/market`; params?: Router.UnknownInputParams; } | { pathname: `/missions`; params?: Router.UnknownInputParams; } | { pathname: `/pack`; params?: Router.UnknownInputParams; } | { pathname: `/tracklist`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/collection`; params?: Router.UnknownInputParams; } | `/collection/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/collection/[genre]`, params: Router.UnknownInputParams & { genre: string | number; } };
    }
  }
}
